<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Site\View\Icon;

defined('KRYSTAL') or die;

?>

<h2 class="page-header"><?php $this->show('Currencies'); ?> <small>(<?= count($currencies); ?>)</small></h2>

<div class="row">
    <div class="col-lg-6">
        <?= Grid::render($currencies, [
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'rowAttributes' => [
                'class' => function($current) use ($entity){
                    return $current['id'] == $entity['id'] ? 'success' : null;
                }
            ],
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#'
                ],

                [
                    'column' => 'code'
                ]
            ],

            'actions' => [
                'edit' => function($row){
                    return Icon::edit(
                        $this->url('Finance:Currency@editAction', $row['id']),
                        $this->translate('Edit this currency')
                    );
                },

                'remove' => function($row){
                    return Icon::remove(
                        $this->url('Finance:Currency@deleteAction', $row['id']),
                        $this->translate('Remove this currency')
                    );
                }
            ]

        ], $this->translator); ?>
    </div>

    <div class="col-lg-6">
        <form action="<?= $this->url('Finance:Currency@saveAction'); ?>" method="POST" autocomplete="off">
          <fieldset>
            <legend><?php $this->show($entity['id'] ? 'Update currency' : 'Add new currency'); ?></legend>

            <?= Element::hidden('id', $entity['id']); ?>

            <div class="form-group">
                <label class="control-label"><?php $this->show('Code'); ?></label>
                <?= Element::text('code', $entity['code'], ['class' => 'form-control']); ?>
            </div>

            <div class="form-group">
                <button data-button="submit" class="btn btn-primary"><?php $this->show('Save'); ?></button>

                <?php if ($entity['id']): ?>
                <a href="<?= $this->url('Finance:Currency@indexAction'); ?>" class="btn btn-danger"><?php $this->show('Cancel'); ?></a>
                <?php endif; ?>
            </div>
          </fieldset>
        </form>
    </div>
</div>

