
<h2 class="page-header"><?php $this->show('Pivot table'); ?></h2>

<table class="table table-bordered table-condensed table-striped">
    <thead>
        <tr>
            <th>Spending</th>
            <th>Amount</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach ($data['data'] as $item): ?>
        <tr class="info">
            <td colspan="2"><?= $item['date']; ?></td>
        </tr>
        
        <?php foreach($item['details'] as $detail): ?>
        <tr>
            <td><?= $detail['spending']; ?></td>
            <td><?= number_format($detail['amount']); ?></td>
        </tr>
        <?php endforeach; ?>
        
        <tr>
            <td colspan="2">
                <span class="pull-right">Total spent: <?= number_format($item['sum']); ?></span>
            </td>
        </tr>
        
        <?php endforeach; ?>
    </tbody>
    
    <tfoot>
        <tr>
            <td>Total: <?= number_format($data['total']); ?></td>
        </tr>
    </tfoot>
</table>