<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Site\View\Icon;

defined('KRYSTAL') or die;

?>

<h2 class="page-header"><?php $this->show('Spendings'); ?> <small>(<?= count($spendings); ?>)</small></h2>

<div class="row">
    <div class="col-lg-6">
        <?= Grid::render($spendings, [
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'rowAttributes' => [
                'class' => function($current) use ($entity){
                    return $current['id'] == $entity['id'] ? 'success' : null;
                }
            ],
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#'
                ],

                [
                    'column' => 'name',
                    'attributes' => [
                        'class' => null
                    ]
                ]
            ],

            'actions' => [
                'edit' => function($spending){
                    return Icon::edit(
                        $this->url('Finance:Spending@editAction', $spending['id']),
                        $this->translate('Edit this spending')
                    );
                },

                'remove' => function($spending){
                    return Icon::remove(
                        $this->url('Finance:Spending@deleteAction', $spending['id']),
                        $this->translate('Remove this spending')
                    );
                }
            ]

        ], $this->translator); ?>
    </div>

    <div class="col-lg-6">
        <form action="<?= $this->url('Finance:Spending@saveAction'); ?>" method="POST" autocomplete="off">
          <fieldset>
            <legend><?php $this->show($entity['id'] ? 'Update spending' : 'Add new spending'); ?></legend>

            <?= Element::hidden('id', $entity['id']); ?>

            <div class="form-group">
                <label class="control-label"><?php $this->show('Name'); ?></label>
                <?= Element::text('name', $entity['name'], ['class' => 'form-control', 'placeholder' => $this->translate('Type your email')]); ?>
            </div>

            <div class="form-group">
                <button data-button="submit" class="btn btn-primary"><?php $this->show('Save'); ?></button>

                <?php if ($entity['id']): ?>
                <a href="<?= $this->url('Finance:Spending@indexAction'); ?>" class="btn btn-danger"><?php $this->show('Cancel'); ?></a>
                <?php endif; ?>
            </div>
          </fieldset>
        </form>
    </div>
</div>

