
<h2 class="page-header"><?php $this->show('Contact us'); ?></h2>

<?php $this->loadPartial('breadcrumbs'); ?>

<?php if ($flashBag->has('success')): ?>
<div class="alert alert-success" role="alert"><i class="glyphicon glyphicon-ok"></i> <?php echo $flashBag->get('success'); ?></div>
<?php endif; ?>

<form class="form-horizontal">
  <fieldset>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label"><?php $this->show('Email'); ?></label>
      <div class="col-lg-10">
        <input type="text" class="form-control" name="email" id="inputEmail" placeholder="<?php $this->show('Type your email'); ?>" />
      </div>
    </div>
    
    <div class="form-group">
      <label for="inputSubject" class="col-lg-2 control-label"><?php $this->show('Subject'); ?></label>
      <div class="col-lg-10">
        <input type="text" class="form-control" name="subject" id="inputSubject" placeholder="<?php $this->show('Type the subject of your email'); ?>" />
      </div>
    </div>
    
    <div class="form-group">
      <label for="textArea" class="col-lg-2 control-label"><?php $this->show('Message'); ?></label>
      <div class="col-lg-10">
        <textarea class="form-control" rows="3" name="message" id="textArea" placeholder="<?php $this->show('Type your message'); ?>"></textarea>
      </div>
    </div>
    
    <div class="form-group">
        <label for="inputCaptcha" class="col-lg-2 control-label"></label>
        <div class="col-lg-10">
            <a href="#" title="<?php $this->show('Click to refresh'); ?>" data-captcha="button-refresh"><img data-captcha="image" src="<?php echo $this->url('Site:Site@captchaAction', null); ?>" /></a>
        </div>
    </div>
    
    <div class="form-group">
        <label for="inputCaptcha" class="col-lg-2 control-label"></label>
        <div class="col-lg-10">
            <input type="text" class="form-control" id="inputCaptcha" name="captcha" placeholder="<?php $this->show("Prove that you are not a bot"); ?>" />
        </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-envelope"></i> <?php $this->show('Submit'); ?></button>
        <button type="reset" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Cancel'); ?></button>
      </div>
    </div>
    
  </fieldset>
</form>
