<div class="jumbotron">
    <h2>Welcome to Krystal Framework!</h2>
    <p>Krystal is a brand new PHP framework, which aims to make web-development enjoyable and cool! If you like writing clean and testable code, then Krystal is a right choice for you!</p>
    <p><a target="_blank" href="https://github.com/krystalframework/krystal.framework" class="btn btn-primary btn-lg" role="button">Check out the repository &raquo;</a></p>
</div>

<div class="row">
    <div class="col-lg-4">
        <h2><i class="glyphicon glyphicon-thumbs-up"></i> Simple and elegant API</h2>
        <p>The framework's API was designed with simplicity in mind, therefore it will be easy to learn the framework. If you have a grasp of basic OOP and MVC, then you'd learn the framework within 2 days!
        It's going to be easy for both beginners or skilled developers!</p>
    </div>

    <div class="col-lg-4">
        <h2><i class="glyphicon glyphicon-file"></i> Almost no configuration</h2>
        <p>You don't need to configure almost anything! Everything is already prepared and waits for you to start adding routes with controllers!</p>
    </div>

    <div class="col-lg-4">
        <h2><i class="glyphicon glyphicon-ok"></i> Best practises</h2>
        <p>Krystal internally follows only best practises, namely Separation of Concerns, SOLID principles and number of proven OOP patterns.</p>
    </div>
</div>
